version: "3"

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - 1880:1880
    volumes:
      - ${NODERED_PATH}/data:/data
    environment:
      - NODE_RED_ENABLE_PROJECTS=true
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-server
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log